#if !canImport(ObjectiveC)
import XCTest

extension FeedOptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeedOptionsTests = [
        ("testMultiFeedOptionDecoding", testMultiFeedOptionDecoding),
        ("testSingleFeedOptionDecoding", testSingleFeedOptionDecoding),
    ]
}

extension FeedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeedTests = [
        ("testFeed", testFeed),
        ("testGuid", testGuid),
        ("testSingleTorrentItem", testSingleTorrentItem),
        ("testSingleTorrentItemPartial", testSingleTorrentItemPartial),
    ]
}

extension StoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StoreTests = [
        ("testAddItems", testAddItems),
        ("testAddStatuses", testAddStatuses),
        ("testFilterByLastStatus", testFilterByLastStatus),
        ("testInitializeEpisodes", testInitializeEpisodes),
        ("testInitializeSeries", testInitializeSeries),
    ]
}

extension TorrentRSSTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TorrentRSSTests = [
        ("testContainsAny", testContainsAny),
        ("testExpandingPath", testExpandingPath),
        ("testFullServerConfig", testFullServerConfig),
        ("testPartialConfig", testPartialConfig),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FeedOptionsTests.__allTests__FeedOptionsTests),
        testCase(FeedTests.__allTests__FeedTests),
        testCase(StoreTests.__allTests__StoreTests),
        testCase(TorrentRSSTests.__allTests__TorrentRSSTests),
    ]
}
#endif
